#include "auto_cattery/level_up_reroll_data.hpp"

#include <array>
#include <fstream>
#include <optional>
#include <sstream>
#include <string>
#include <system_error>

#include <nlohmann/json.hpp>
#include <windows.h>

namespace autocattery {
namespace {

using Json = nlohmann::json;

constexpr std::array<const char*, 7> kBaseClasses{
    "Fighter", "Hunter", "Mage", "Medic", "Tank", "Thief", "Colorless"};
constexpr std::array<const char*, 7> kAdvancedClasses{
    "Monk", "Butcher", "Druid", "Tinkerer", "Necromancer", "Psychic", "Jester"};

std::string Render(
    const std::array<const char*, 7>& classes,
    std::size_t reroll_count) {
    std::ostringstream output;
    output << "// Generated by AutoCattery. Restart the game after changing this value.\n";
    for (const char* name : classes) {
        output << name << " { innate_passives { AddLevelUpRerolls "
               << reroll_count << " } }\n";
    }
    return output.str();
}

Result<void> WriteFile(
    const std::filesystem::path& path,
    const std::string& contents) {
    std::ofstream stream(path, std::ios::binary | std::ios::trunc);
    if (!stream) {
        return {ErrorCode::ConfigInvalid,
                "cannot create a temporary level-up reroll data file"};
    }
    stream.write(contents.data(), static_cast<std::streamsize>(contents.size()));
    stream.flush();
    if (!stream) {
        return {ErrorCode::ConfigInvalid,
                "cannot write a temporary level-up reroll data file"};
    }
    return {};
}

std::optional<std::string> ReadExisting(const std::filesystem::path& path) {
    std::ifstream stream(path, std::ios::binary);
    if (!stream) return std::nullopt;
    std::ostringstream output;
    output << stream.rdbuf();
    return output.str();
}

Result<void> Replace(
    const std::filesystem::path& temporary,
    const std::filesystem::path& destination) {
    if (MoveFileExW(
            temporary.c_str(), destination.c_str(),
            MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH) == 0) {
        return {ErrorCode::ConfigInvalid,
                "cannot atomically replace a level-up reroll data file"};
    }
    return {};
}

void Restore(
    const std::filesystem::path& path,
    const std::optional<std::string>& previous) noexcept {
    std::error_code error;
    if (!previous) {
        std::filesystem::remove(path, error);
        return;
    }
    const auto temporary = path.wstring() + L".rollback.tmp";
    if (!WriteFile(temporary, *previous)) return;
    (void)Replace(temporary, path);
}

}  // namespace

Result<std::filesystem::path> ResolveAutoCatteryDataRoot(
    const std::filesystem::path& mewtator_config) {
    std::ifstream stream(mewtator_config, std::ios::binary);
    if (!stream) {
        return {{}, ErrorCode::ConfigInvalid,
                "Mewtator config.json is unavailable"};
    }
    try {
        Json config;
        stream >> config;
        const auto mod_folder = config.at("mod_folder").get<std::string>();
        if (mod_folder.empty()) {
            return {{}, ErrorCode::ConfigInvalid,
                    "Mewtator mod_folder is empty"};
        }
        auto mod_root = std::filesystem::path(mod_folder);
        if (mod_root.is_relative()) {
            mod_root = mewtator_config.parent_path() / mod_root;
        }
        return {std::filesystem::absolute(mod_root) / L"AutoCattery"};
    } catch (const Json::exception& error) {
        return {{}, ErrorCode::ConfigInvalid,
                "invalid Mewtator config.json: " + std::string(error.what())};
    }
}

Result<void> WriteLevelUpRerollData(
    const std::filesystem::path& data_mod_root,
    std::size_t reroll_count) {
    if (data_mod_root.empty() || reroll_count > 99) {
        return {ErrorCode::ConfigInvalid,
                "level-up reroll count must be between 0 and 99"};
    }
    const auto directory = data_mod_root / L"data" / L"classes";
    std::error_code error;
    std::filesystem::create_directories(directory, error);
    if (error) {
        return {ErrorCode::ConfigInvalid,
                "cannot create the level-up reroll data directory"};
    }

    const auto base = directory / L"classes.gon.merge";
    const auto advanced = directory / L"advanced_classes.gon.merge";
    const auto base_temporary = base.wstring() + L".candidate.tmp";
    const auto advanced_temporary = advanced.wstring() + L".candidate.tmp";
    std::filesystem::remove(base_temporary, error);
    std::filesystem::remove(advanced_temporary, error);
    const auto base_text = Render(kBaseClasses, reroll_count);
    const auto advanced_text = Render(kAdvancedClasses, reroll_count);
    auto result = WriteFile(base_temporary, base_text);
    if (!result) return result;
    result = WriteFile(advanced_temporary, advanced_text);
    if (!result) {
        std::filesystem::remove(base_temporary, error);
        return result;
    }

    const auto previous_base = ReadExisting(base);
    const auto previous_advanced = ReadExisting(advanced);
    result = Replace(base_temporary, base);
    if (!result) {
        std::filesystem::remove(advanced_temporary, error);
        return result;
    }
    result = Replace(advanced_temporary, advanced);
    if (!result) {
        Restore(base, previous_base);
        Restore(advanced, previous_advanced);
        std::filesystem::remove(advanced_temporary, error);
        return result;
    }
    return {};
}

}  // namespace autocattery
